version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.6.8
    steps:
      - checkout
      - run: poetry build
      - run: poetry install
      - run: poetry run pytest -p no:warnings

workflows:
  build-and-test:
    jobs:
      - build-and-test
