version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7.5
    steps:
      - checkout
      - run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python && source $HOME/.poetry/env
      - run: poetry build
      - run: poetry install
  test:
    docker:
      - image: circleci/python:3.7.5
    steps:
      - run: poetry run pytest

workflows:
  build_and_test:
    jobs:
      - build
      - test
