version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.7.5
    steps:
      - checkout
      - run: poetry build
      - run: poetry install
      - run: poetry run pytest

workflows:
  build_and_test:
    jobs:
      - build-and-test
