version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7.5
    steps:
      - checkout
      - run:
        name: "Get Poetry"
        command: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python && source $HOME/.poetry/env
      - run:
        name: "Build the package"
        command: poetry build
      - run:
        name: "Install dependencies"
        command: poetry install
  test:
    docker:
      - image: circleci/python:3.7.5
    steps:
      - run:
        name: "Run tests"
        command: poetry run pytest

workflows:
  build_and_test:
    jobs:
      - build
      - test
